export const Avatars = [
    {
      name: 'Sung Jinwoo',
      image: require('../assets/avtar/sungJinwoo.png'),
      powers: ['Shadow Monarch', 'Stealth'],
      gender: 'male',
      description: 'The main protagonist with the power of shadows.',
      rankLevel: 'S',
      fullCharacterImage: require('../assets/avatars/sungJinwoo.png'),
      backgroundImage: require('../assets/banner/main.jpg'),
    },
    {
      name: 'Alicia Blanche',
      image: require('../assets/avtar/aliciaBlanche.png'),
      powers: ['Ice magic', 'AoE Freeze'],
      gender: 'female',
      description: 'A powerful water-element mage.',
      rankLevel: 'S',
      fullCharacterImage: require('../assets/avatars/aliciaBlanche.png'),
      backgroundImage: require('../assets/banner/pink.jpg'),
    },
    {
      name: 'Cha Hae-In',
      image: require('../assets/avtar/chaHarin.png'),
      powers: ['Swordmaster', 'Aura Slash'],
      gender: 'female',
      description: 'A high-ranking hunter with exceptional sword skills.',
      rankLevel: 'S',
      fullCharacterImage: require('../assets/avatars/chaHarin.png'),
      backgroundImage: require('../assets/banner/redyellow.jpg'),
    },
    {
      name: 'Thomas Andre',
      image: require('../assets/avtar/thomasAndre.png'),
      powers: ['Brute Strength', 'Body Reinforcement'],
      gender: 'male',
      description: 'One of the top American hunters.',
      rankLevel: 'S',
      fullCharacterImage: require('../assets/avatars/thomasAndre.png'),
      backgroundImage: require('../assets/banner/volcanic_outburst_thumb.jpg'),
    },
    {
      name: 'Baek Yoonho',
      image: require('../assets/avtar/baekyoonho.png'),
      powers: ['Beast Transformation'],
      gender: 'male',
      description: 'Leader of the White Tiger Guild.',
      rankLevel: 'S',
      fullCharacterImage: require('../assets/avatars/baekyoonho.png'),
      backgroundImage: require('../assets/banner/impale_thumb.jpg'),
    },
    {
      name: 'Go Gunhee',
      image: require('../assets/avtar/goGunhee.png'), // Placeholder image
      powers: ['Chairman aura'],
      gender: 'male',
      description: 'Chairman of the Korean Hunters Association.',
      rankLevel: 'S',
      fullCharacterImage: require('../assets/avatars/goGunhee.png'),
      backgroundImage: require('../assets/banner/spiked_shell_thumb.jpg'),
    },
    {
      name: 'Yoo Jinho',
      image: require('../assets/avtar/yooJinho.png'),
      powers: ['Shield', 'Support'],
      gender: 'male',
      description: 'Jinwoo’s loyal friend and guild officer.',
      rankLevel: 'A',
      fullCharacterImage: require('../assets/avatars/yooJinho.png'),
      backgroundImage: require('../assets/banner/inferno_slice_thumb.jpg'),
    },
    {
      name: 'Lee Joohee',
      image: require('../assets/avtar/LeeJoohee.png'),
      powers: ['Healing'],
      gender: 'female',
      description: 'A gentle healer and early companion of Jinwoo.',
      rankLevel: 'B',
      fullCharacterImage: require('../assets/avatars/LeeJoohee.png'),
      backgroundImage: require('../assets/banner/rejuvenate_thumb.jpg'),
    },
    {
      name: 'Woo Jinchul',
      image: require('../assets/avtar/WooJinchul.png'),
      powers: ['Super Speed'],
      gender: 'male',
      description: 'Chief Inspector of the Monitoring Division.',
      rankLevel: 'A',
      fullCharacterImage: require('../assets/avatars/WooJinchul.png'),
      backgroundImage: require('../assets/banner/spiked_shell_thumb.jpg'),
    },
    {
      name: 'Emma Laurant',
      image: require('../assets/avtar/emmaLaurant.png'),
      powers: ['Fire Manipulation'],
      gender: 'female',
      description: 'An international mage with fiery skills.',
      rankLevel: 'S',
      fullCharacterImage: require('../assets/avatars/emmaLaurant.png'),
      backgroundImage: require('../assets/banner/firestorm_thumb.jpg'),
    },
    {
      name: 'Kang Taeshik',
      image: require('../assets/avtar/KangTaeshik.png'),
      powers: ['Poison Dagger'],
      gender: 'male',
      description: 'A rogue-type assassin hunter.',
      rankLevel: 'A',
      fullCharacterImage: require('../assets/avatars/KangTaeshik.png'),
      backgroundImage: require('../assets/banner/frantic_lunge_thumb.jpg'),
    },
    {
      name: 'Min Byung-gu',
      image: require('../assets/avtar/MinByung-gu.png'),
      powers: ['Advanced Healing'],
      gender: 'male',
      description: 'Top-tier healer with immense mana control.',
      rankLevel: 'S',
      fullCharacterImage: require('../assets/avatars/MinByung-gu.png'),
      backgroundImage: require('../assets/banner/hydro_cleave_thumb.jpg'),
    },
    {
      name: 'Han Song Yi',
      image: require('../assets/avtar/HanSongYi.png'),
      powers: ['Undisclosed'],
      gender: 'female',
      description: 'Han Song-Yi, Jinah close friend and a former E-Rank Hunter with surprising resilience.',
      rankLevel: 'B',
      fullCharacterImage: require('../assets/avatars/HanSongYi.png'),
      backgroundImage: require('../assets/banner/spiked_shell_thumb.jpg'),
    },
    {
        name: 'Amamiya Mirei',
        image: require('../assets/avtar/AmamiyaMirei.png'),
        powers: ['Assassin', 'Swordsmanship'],
        gender: 'female',
        description: 'Amamiya Mirei, Japan swift S-Rank assassin wielding soul-powered swordsmanship.',
        rankLevel: 'S',
        fullCharacterImage: require('../assets/avatars/AmamiyaMirei.png'),
        backgroundImage: require('../assets/banner/pink.jpg'),
      },
      {
        name: 'Charlotte',
        image: require('../assets/avtar/charlotte.png'),
        powers: ['Doll Magic', 'Dark Magic'],
        gender: 'female',
        description: 'Charlotte, the mischievous A-Rank dark mage from England with her animated dolls.',
        rankLevel: 'A',
        fullCharacterImage: require('../assets/avatars/charlotte.png'),
        backgroundImage: require('../assets/banner/pink.jpg'),
      },
      {
        name: 'Choi Jongin',
        image: require('../assets/avtar/choiJongin.png'),
        powers: ['Fire Magic', 'Leader'],
        gender: 'male',
        description: 'Choi Jong-In, Korea top S-Rank fire mage and leader of the Hunters Guild.',
        rankLevel: 'S',
        fullCharacterImage: require('../assets/avatars/choiJongin.png'),
        backgroundImage: require('../assets/banner/volcanic_outburst_thumb.jpg'),
      },
      {
        name: 'Esil Radiru',
        image: require('../assets/avtar/esilRadiru.png'),
        powers: ['Princess', 'Assassin'],
        gender: 'female',
        description: 'Esil Radiru is a short-lived character in Solo Leveling who is a member of the Red Gate.',
        rankLevel: 'A',
        fullCharacterImage: require('../assets/avatars/esilRadiru.png'),
        backgroundImage: require('../assets/banner/redyellow.jpg'),
      },
      {
        name: 'Gina',
        image: require('../assets/avtar/gina.png'),
        powers: ['psychokinesis', 'gravity control'],
        gender: 'female',
        description: 'A-Rank Hunter known for her ability to control psychokinesis and gravity',
        rankLevel: 'A',
        fullCharacterImage: require('../assets/avatars/gina.png'),
        backgroundImage: require('../assets/banner/skewer_thumb.jpg'),
      },
      // {
      //   name: 'Han Se MI',
      //   image: require('../assets/avtar/hanSeMI.png'),
      //   powers: [],
      //   gender: '',
      //   description: '',
      //   rankLevel: '',
      //   fullCharacterImage: require('../assets/avatars/hanSeMI.png'),
      //   backgroundImage: require('../assets/banner/pierce_thumb.jpg'),
      // },
      // {
      //   name: 'Harper',
      //   image: require('../assets/avtar/harper.png'),
      //   powers: [],
      //   gender: '',
      //   description: '',
      //   rankLevel: '',
      //   fullCharacterImage: require('../assets/avatars/harper.png'),
      //   backgroundImage: require('../assets/banner/purple.jpg'),
      // },
      // {
      //   name: 'Hwang Dongsoo',
      //   image: require('../assets/avtar/hwangDongsoo.png'),
      //   powers: [],
      //   gender: '',
      //   description: '',
      //   rankLevel: '',
      //   fullCharacterImage: require('../assets/avatars/hwangDongsoo.png'),
      //   backgroundImage: require('../assets/banner/earth.jpg'),
      // },
      // {
      //   name: 'Hwang Dongsuk',
      //   image: require('../assets/avtar/HwangDongsuk.png'),
      //   powers: [],
      //   gender: '',
      //   description: '',
      //   rankLevel: '',
      //   fullCharacterImage: require('../assets/avatars/HwangDongsuk.png'),
      //   backgroundImage: require('../assets/banner/lacerate_thumb.jpg'),
      // },
      // {
      //   name: 'Isla Wright',
      //   image: require('../assets/avtar/islaWright.png'),
      //   powers: [],
      //   gender: '',
      //   description: '',
      //   rankLevel: '',
      //   fullCharacterImage: require('../assets/avatars/islaWright.png'),
      //   backgroundImage: require('../assets/banner/pierce_thumb.jpg'),
      // },
      // {
      //   name: 'Jo Kyuhwan',
      //   image: require('../assets/avtar/JoKyuhwan.png'),
      //   powers: [],
      //   gender: '',
      //   description: '',
      //   rankLevel: '',
      //   fullCharacterImage: require('../assets/avatars/JoKyuhwan.png'),
      //   backgroundImage: require('../assets/banner/jitters_thumb.jpg'),
      // },
      // {
      //   name: 'Kim Chul',
      //   image: require('../assets/avtar/KimChul.png'),
      //   powers: [],
      //   gender: '',
      //   description: '',
      //   rankLevel: '',
      //   fullCharacterImage: require('../assets/avatars/KimChul.png'),
      //   backgroundImage: require('../assets/banner/skewer_thumb.jpg'),
      // },
      // {
      //   name: 'Kim Sangshik',
      //   image: require('../assets/avtar/kimSangshik.png'),
      //   powers: [],
      //   gender: '',
      //   description: '',
      //   rankLevel: '',
      //   fullCharacterImage: require('../assets/avatars/kimSangshik.png'),
      //   backgroundImage: require('../assets/banner/isolate_thumb.jpg'),
      // },
      // {
      //   name: 'Lee Bora',
      //   image: require('../assets/avtar/LeeBora.png'),
      //   powers: [],
      //   gender: '',
      //   description: '',
      //   rankLevel: '',
      //   fullCharacterImage: require('../assets/avatars/LeeBora.png'),
      //   backgroundImage: require('../assets/banner/pink.jpg'),
      // },
      // {
      //   name: 'Lim Taegyu',
      //   image: require('../assets/avtar/limTaegyu.png'),
      //   powers: [],
      //   gender: '',
      //   description: '',
      //   rankLevel: '',
      //   fullCharacterImage: require('../assets/avatars/limTaegyu.png'),
      //   backgroundImage: require('../assets/banner/hydro_gulp_thumb.jpg'),
      // },
      // {
      //   name: 'Meilin Fisher',
      //   image: require('../assets/avtar/meilinFisher.png'),
      //   powers: [],
      //   gender: '',
      //   description: '',
      //   rankLevel: '',
      //   fullCharacterImage: require('../assets/avatars/meilinFisher.png'),
      //   backgroundImage: require('../assets/banner/smooth_swipe_thumb.jpg'),
      // },
      // {
      //   name: 'Park Heejin',
      //   image: require('../assets/avtar/ParkHeejin.png'),
      //   powers: [],
      //   gender: '',
      //   description: '',
      //   rankLevel: '',
      //   fullCharacterImage: require('../assets/avatars/ParkHeejin.png'),
      //   backgroundImage: require('../assets/banner/impale_thumb.jpg'),
      // },
      {
        name: 'Seorin',
        image: require('../assets/avtar/seorin.png'),
        powers: ['rising star'],
        gender: 'female',
        description: 'An administrative staff member with the Korean Hunters Association.',
        rankLevel: 'A',
        fullCharacterImage: require('../assets/avatars/seorin.png'),
        backgroundImage: require('../assets/banner/tackle_thumb.jpg'),
      },
      {
        name: 'Shimizu Akari',
        image: require('../assets/avtar/shimizuAkari.png'),
        powers: ['fire', 'storm attack'],
        gender: 'female',
        description: 'An S-Rank Hunter in the Blade Guild',
        rankLevel: 'S',
        fullCharacterImage: require('../assets/avatars/shimizuAkari.png'),
        backgroundImage: require('../assets/banner/going_nuclear_thumb.jpg'),
      },
      {
        name: 'Song Chiyul',
        image: require('../assets/avtar/SongChiyul.png'),
        powers: ['Swordsmanship', 'Kumdo'],
        gender: 'male',
        description: 'a Korean C-Rank Hunter and a kumdo teacher',
        rankLevel: 'C',
        fullCharacterImage: require('../assets/avatars/SongChiyul.png'),
        backgroundImage: require('../assets/banner/shadowflame_thumb.jpg'),
      },
      {
        name: 'Tawata Kanae',
        image: require('../assets/avtar/tawataKanae.png'),
        powers: ['inflict incredible damage', 'summon monsters'],
        gender: 'female',
        description: 'An S-Rank hunter in the Blade Guild.',
        rankLevel: 'S',
        fullCharacterImage: require('../assets/avatars/tawataKanae.png'),
        backgroundImage: require('../assets/banner/pink.jpg'),
      },
      {
        name: 'Yooshoohyun',
        image: require('../assets/avtar/Yooshoohyun.png'),
        powers: ["Trick Shot", "Sniper"],
        gender: 'female',
        description: 'A-rank hunter who also works as a popular model and actress',
        rankLevel: 'A',
        fullCharacterImage: require('../assets/avatars/Yooshoohyun.png'),
        backgroundImage: require('../assets/banner/purple.jpg'),
      },
  ];
  