export const Avatars = [
    {
      name: 'Sung Jinwoo',
      image: require('../assets/avtar/sungJinwoo.png'),
      powers: ['Shadow Monarch', 'Stealth'],
      gender: 'male',
      description: 'The main protagonist with the power of shadows.',
      rankLevel: 'S',
      fullCharacterImage: require('../assets/avatars/sungJinwoo.png'),
    },
    {
      name: 'Alicia Blanche',
      image: require('../assets/avtar/aliciaBlanche.png'),
      powers: ['Ice magic', 'AoE Freeze'],
      gender: 'female',
      description: 'A powerful water-element mage.',
      rankLevel: 'S',
      fullCharacterImage: require('../assets/avatars/aliciaBlanche.png'),
    },
    {
      name: 'Cha Hae-In',
      image: require('../assets/avtar/chaHarin.png'),
      powers: ['Swordmaster', 'Aura Slash'],
      gender: 'female',
      description: 'A high-ranking hunter with exceptional sword skills.',
      rankLevel: 'S',
      fullCharacterImage: require('../assets/avatars/chaHarin.png'),
    },
    {
      name: 'Thomas Andre',
      image: require('../assets/avtar/thomasAndre.png'),
      powers: ['Brute Strength', 'Body Reinforcement'],
      gender: 'male',
      description: 'One of the top American hunters.',
      rankLevel: 'S',
      fullCharacterImage: require('../assets/avatars/thomasAndre.png'),
    },
    {
      name: 'Baek Yoonho',
      image: require('../assets/avtar/baekyoonho.png'),
      powers: ['Beast Transformation'],
      gender: 'male',
      description: 'Leader of the White Tiger Guild.',
      rankLevel: 'S',
      fullCharacterImage: require('../assets/avatars/baekyoonho.png'),
    },
    {
      name: 'Go Gunhee',
      image: require('../assets/avtar/goGunhee.png'), // Placeholder image
      powers: ['Chairman aura'],
      gender: 'male',
      description: 'Chairman of the Korean Hunters Association.',
      rankLevel: 'S',
      fullCharacterImage: require('../assets/avatars/goGunhee.png'),
    },
    {
      name: 'Yoo Jinho',
      image: require('../assets/avtar/yooJinho.png'),
      powers: ['Shield', 'Support'],
      gender: 'male',
      description: 'Jinwoo’s loyal friend and guild officer.',
      rankLevel: 'A',
      fullCharacterImage: require('../assets/avatars/yooJinho.png'),
    },
    {
      name: 'Lee Joohee',
      image: require('../assets/avtar/LeeJoohee.png'),
      powers: ['Healing'],
      gender: 'female',
      description: 'A gentle healer and early companion of Jinwoo.',
      rankLevel: 'B',
      fullCharacterImage: require('../assets/avatars/LeeJoohee.png'),
    },
    {
      name: 'Woo Jinchul',
      image: require('../assets/avtar/WooJinchul.png'),
      powers: ['Super Speed'],
      gender: 'male',
      description: 'Chief Inspector of the Monitoring Division.',
      rankLevel: 'A',
      fullCharacterImage: require('../assets/avatars/WooJinchul.png'),
    },
    {
      name: 'Emma Laurant',
      image: require('../assets/avtar/emmaLaurant.png'),
      powers: ['Fire Manipulation'],
      gender: 'female',
      description: 'An international mage with fiery skills.',
      rankLevel: 'S',
      fullCharacterImage: require('../assets/avatars/emmaLaurant.png'),
    },
    {
      name: 'Kang Taeshik',
      image: require('../assets/avtar/KangTaeshik.png'),
      powers: ['Poison Dagger'],
      gender: 'male',
      description: 'A rogue-type assassin hunter.',
      rankLevel: 'A',
      fullCharacterImage: require('../assets/avatars/KangTaeshik.png'),
    },
    {
      name: 'Min Byung-gu',
      image: require('../assets/avtar/MinByung-gu.png'),
      powers: ['Advanced Healing'],
      gender: 'male',
      description: 'Top-tier healer with immense mana control.',
      rankLevel: 'S',
      fullCharacterImage: require('../assets/avatars/MinByung-gu.png'),
    },
    {
      name: 'Han Song Yi',
      image: require('../assets/avtar/HanSongYi.png'),
      powers: ['Undisclosed'],
      gender: 'female',
      description: 'A mysterious hunter.',
      rankLevel: 'B',
      fullCharacterImage: require('../assets/avatars/HanSongYi.png'),
    },
    {
        name: 'Amamiya Mirei',
        image: require('../assets/avtar/AmamiyaMirei.png'),
        powers: [],
        gender: '',
        description: '',
        rankLevel: '',
        fullCharacterImage: require('../assets/avatars/AmamiyaMirei.png'),
      },
      {
        name: 'Charlotte',
        image: require('../assets/avtar/charlotte.png'),
        powers: [],
        gender: '',
        description: '',
        rankLevel: '',
        fullCharacterImage: require('../assets/avatars/charlotte.png'),
      },
      {
        name: 'Choi Jongin',
        image: require('../assets/avtar/choiJongin.png'),
        powers: [],
        gender: '',
        description: '',
        rankLevel: '',
        fullCharacterImage: require('../assets/avatars/choiJongin.png'),
      },
      {
        name: 'Esil Radiru',
        image: require('../assets/avtar/esilRadiru.png'),
        powers: [],
        gender: '',
        description: '',
        rankLevel: '',
        fullCharacterImage: require('../assets/avatars/esilRadiru.png'),
      },
      {
        name: 'Gina',
        image: require('../assets/avtar/gina.png'),
        powers: [],
        gender: '',
        description: '',
        rankLevel: '',
        fullCharacterImage: require('../assets/avatars/gina.png'),
      },
      {
        name: 'Han Se MI',
        image: require('../assets/avtar/hanSeMI.png'),
        powers: [],
        gender: '',
        description: '',
        rankLevel: '',
        fullCharacterImage: require('../assets/avatars/hanSeMI.png'),
      },
      {
        name: 'Harper',
        image: require('../assets/avtar/harper.png'),
        powers: [],
        gender: '',
        description: '',
        rankLevel: '',
        fullCharacterImage: require('../assets/avatars/harper.png'),
      },
      {
        name: 'Hwang Dongsoo',
        image: require('../assets/avtar/hwangDongsoo.png'),
        powers: [],
        gender: '',
        description: '',
        rankLevel: '',
        fullCharacterImage: require('../assets/avatars/hwangDongsoo.png'),
      },
      {
        name: 'Hwang Dongsuk',
        image: require('../assets/avtar/HwangDongsuk.png'),
        powers: [],
        gender: '',
        description: '',
        rankLevel: '',
        fullCharacterImage: require('../assets/avatars/HwangDongsuk.png'),
      },
      {
        name: 'Isla Wright',
        image: require('../assets/avtar/islaWright.png'),
        powers: [],
        gender: '',
        description: '',
        rankLevel: '',
        fullCharacterImage: require('../assets/avatars/islaWright.png'),
      },
      {
        name: 'Jo Kyuhwan',
        image: require('../assets/avtar/JoKyuhwan.png'),
        powers: [],
        gender: '',
        description: '',
        rankLevel: '',
        fullCharacterImage: require('../assets/avatars/JoKyuhwan.png'),
      },
      {
        name: 'Kim Chul',
        image: require('../assets/avtar/KimChul.png'),
        powers: [],
        gender: '',
        description: '',
        rankLevel: '',
        fullCharacterImage: require('../assets/avatars/KimChul.png'),
      },
      {
        name: 'Kim Sangshik',
        image: require('../assets/avtar/kimSangshik.png'),
        powers: [],
        gender: '',
        description: '',
        rankLevel: '',
        fullCharacterImage: require('../assets/avatars/kimSangshik.png'),
      },
      {
        name: 'Lee Bora',
        image: require('../assets/avtar/LeeBora.png'),
        powers: [],
        gender: '',
        description: '',
        rankLevel: '',
        fullCharacterImage: require('../assets/avatars/LeeBora.png'),
      },
      {
        name: 'Lim Taegyu',
        image: require('../assets/avtar/limTaegyu.png'),
        powers: [],
        gender: '',
        description: '',
        rankLevel: '',
        fullCharacterImage: require('../assets/avatars/limTaegyu.png'),
      },
      {
        name: 'Meilin Fisher',
        image: require('../assets/avtar/meilinFisher.png'),
        powers: [],
        gender: '',
        description: '',
        rankLevel: '',
        fullCharacterImage: require('../assets/avatars/meilinFisher.png'),
      },
      {
        name: 'Park Heejin',
        image: require('../assets/avtar/ParkHeejin.png'),
        powers: [],
        gender: '',
        description: '',
        rankLevel: '',
        fullCharacterImage: require('../assets/avatars/ParkHeejin.png'),
      },
      {
        name: 'Seorin',
        image: require('../assets/avtar/seorin.png'),
        powers: [],
        gender: '',
        description: '',
        rankLevel: '',
        fullCharacterImage: require('../assets/avatars/seorin.png'),
      },
      {
        name: 'Shimizu Akari',
        image: require('../assets/avtar/shimizuAkari.png'),
        powers: [],
        gender: '',
        description: '',
        rankLevel: '',
        fullCharacterImage: require('../assets/avatars/shimizuAkari.png'),
      },
      {
        name: 'Song Chiyul',
        image: require('../assets/avtar/SongChiyul.png'),
        powers: [],
        gender: '',
        description: '',
        rankLevel: '',
        fullCharacterImage: require('../assets/avatars/SongChiyul.png'),
      },
      {
        name: 'Tawata Kanae',
        image: require('../assets/avtar/tawataKanae.png'),
        powers: [],
        gender: '',
        description: '',
        rankLevel: '',
        fullCharacterImage: require('../assets/avatars/tawataKanae.png'),
      },
      {
        name: 'Yooshoohyun',
        image: require('../assets/avtar/Yooshoohyun.png'),
        powers: [],
        gender: '',
        description: '',
        rankLevel: '',
        fullCharacterImage: require('../assets/avatars/Yooshoohyun.png'),
      },
  ];
  